# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: action.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'action.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x63tion.proto\x12\x0fneural_chromium\"\x8d\x02\n\x06\x41\x63tion\x12\x13\n\x0bsequence_id\x18\x01 \x01(\r\x12\x14\n\x0ctimestamp_us\x18\x02 \x01(\x03\x12\x33\n\x08navigate\x18\x03 \x01(\x0b\x32\x1f.neural_chromium.NavigateActionH\x00\x12-\n\x05input\x18\x04 \x01(\x0b\x32\x1c.neural_chromium.InputActionH\x00\x12\x39\n\x0binteraction\x18\x05 \x01(\x0b\x32\".neural_chromium.InteractionActionH\x00\x12/\n\x06script\x18\x06 \x01(\x0b\x32\x1d.neural_chromium.ScriptActionH\x00\x42\x08\n\x06\x61\x63tion\".\n\x0eNavigateAction\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x07new_tab\x18\x02 \x01(\x08\"+\n\x0bInputAction\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06submit\x18\x02 \x01(\x08\"\xa9\x02\n\x11InteractionAction\x12;\n\x04type\x18\x01 \x01(\x0e\x32-.neural_chromium.InteractionAction.ActionType\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\x11\n\tscroll_dx\x18\x04 \x01(\x05\x12\x11\n\tscroll_dy\x18\x05 \x01(\x05\x12\x10\n\x08key_code\x18\x06 \x01(\t\x12\x11\n\tmodifiers\x18\x07 \x01(\x05\"v\n\nActionType\x12\x0e\n\nCLICK_LEFT\x10\x00\x12\x0f\n\x0b\x43LICK_RIGHT\x10\x01\x12\x10\n\x0c\x43LICK_MIDDLE\x10\x02\x12\x0f\n\x0b\x44\x43LICK_LEFT\x10\x03\x12\n\n\x06SCROLL\x10\x04\x12\t\n\x05HOVER\x10\x05\x12\r\n\tKEY_PRESS\x10\x06\"\x1e\n\x0cScriptAction\x12\x0e\n\x06script\x18\x01 \x01(\tB\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_ACTION']._serialized_start=34
  _globals['_ACTION']._serialized_end=303
  _globals['_NAVIGATEACTION']._serialized_start=305
  _globals['_NAVIGATEACTION']._serialized_end=351
  _globals['_INPUTACTION']._serialized_start=353
  _globals['_INPUTACTION']._serialized_end=396
  _globals['_INTERACTIONACTION']._serialized_start=399
  _globals['_INTERACTIONACTION']._serialized_end=696
  _globals['_INTERACTIONACTION_ACTIONTYPE']._serialized_start=578
  _globals['_INTERACTIONACTION_ACTIONTYPE']._serialized_end=696
  _globals['_SCRIPTACTION']._serialized_start=698
  _globals['_SCRIPTACTION']._serialized_end=728
# @@protoc_insertion_point(module_scope)
