# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shared_memory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shared_memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13shared_memory.proto\x12\x0fneural_chromium\"q\n\x0bVideoHeader\x12\r\n\x05magic\x18\x01 \x01(\r\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x0e\n\x06stride\x18\x04 \x01(\r\x12\x0e\n\x06\x66ormat\x18\x05 \x01(\r\x12\x14\n\x0ctimestamp_us\x18\x06 \x01(\x03\"i\n\x0b\x41udioHeader\x12\r\n\x05magic\x18\x01 \x01(\r\x12\x13\n\x0bsample_rate\x18\x02 \x01(\r\x12\x10\n\x08\x63hannels\x18\x03 \x01(\r\x12\x0e\n\x06\x66rames\x18\x04 \x01(\r\x12\x14\n\x0ctimestamp_us\x18\x05 \x01(\x03\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shared_memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_VIDEOHEADER']._serialized_start=40
  _globals['_VIDEOHEADER']._serialized_end=153
  _globals['_AUDIOHEADER']._serialized_start=155
  _globals['_AUDIOHEADER']._serialized_end=260
# @@protoc_insertion_point(module_scope)
